file:
  savePath: /opt/checkcode/file

spring:
  datasource:
    url: jdbc:mysql://172.16.0.10:3306/db_code?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: cz@com101
