file:
  savePath: /opt/checkcode/file

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_code?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

logging:
  paths: /opt/checkcode/logs
